Traceback (most recent call last):
  File "/home/melina/Desktop/MLops/S1_MLops/main.py", line 29, in <module>
    model = model.to(self.device)
NameError: name 'self' is not defined